POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "titulo": "Aprende Node.js",
    "lenguaje": "javascript",
    "vistas": 45676,
    "nivel": "basico"
}

###
PUT http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "titulo": "C# intermedio con proyectos",
    "lenguaje": "C#",
    "vistas": 123996,
    "nivel": "intermedio"
}

###
PATCH http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: application/json

{
    "titulo": "Python intermedio con proyectos",
    "vistas": 123006
}

###
DELETE http://localhost:3000/api/cursos/programacion/1 HTTP/1.1

//PARA MATH

###
POST http://localhost:3000/api/cursos/matematicas HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "titulo": "Aprende Derivadas",
    "tema": "Diferencial",
    "vistas": 45696,
    "nivel": "intermedio"
}

###
PUT http://localhost:3000/api/cursos/matematicas/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "titulo": "Ecuaciones Diferenciales",
    "tema": "Ecuaciones",
    "vistas": 10000,
    "nivel": "basico"
}

###
PATCH http://localhost:3000/api/cursos/matematicas/2 HTTP/1.1
Content-Type: application/json

{
    "titulo": "Bidó el mejol profesol del Itla",
    "vistas": 100000
}

###
DELETE  http://localhost:3000/api/cursos/matematicas/1 HTTP/1.1